# Generated by Django 5.1.6 on 2025-03-10 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('accountid', models.AutoField(db_column='accountID', primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=50, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=100, unique=True)),
                ('role', models.CharField(blank=True, max_length=8, null=True)),
            ],
            options={
                'db_table': 'account',
            },
        ),
    ]
