# Generated by Django 5.1.6 on 2025-03-10 15:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('customerid', models.AutoField(db_column='customerID', primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('address', models.TextField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, max_length=6, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('accountid', models.OneToOneField(blank=True, db_column='accountID', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='accounts.account')),
            ],
            options={
                'db_table': 'customer',
            },
        ),
    ]
